#ifndef OSLDGRAPHICSENGINE_GLOBAL_H
#define OSLDGRAPHICSENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OSLDGRAPHICSENGINE_LIBRARY)
#  define OSLDGRAPHICSENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define OSLDGRAPHICSENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OSLDGRAPHICSENGINE_GLOBAL_H
